/**
 * The texts of the Podatki → PIT tab. Kept here, apart from translations.ts, so the tab is one unit; the
 * English set must have every key of the Polish one (the type says so).
 */

const pl = {
  title: 'PIT-11 i PIT-4R',
  heroYear: 'rok podatkowy',
  heroEmpty: 'Brak wspólnot w tym roku',
  heroCount: '{n} wspólnot',
  heroPeople: '{n} PIT-11',
  heroAdvances: 'zaliczki {kwota}',
  heroReview: 'do przeglądu: {n}',
  heroFiled: 'złożone: {done} z {total}',
  yearNew: '{rok} (nowy)',
  yearPrev: 'Poprzedni rok',
  yearNext: 'Następny rok',
  year: 'Rok',
  formUnconfirmed:
    'Wzór formularzy na {rok} r. nie jest jeszcze potwierdzony: używam PIT-11 (29) i PIT-4R (13) z poprzedniego roku. Bramka e-Deklaracji sprawdzi plik schematem — jeśli MF opublikował nowy wzór, plik zostanie odrzucony, nie źle złożony.',
  formMissing: 'Dla roku {rok} aplikacja nie zna wzorów PIT-11 i PIT-4R — plików nie da się wygenerować.',
  search: 'Szukaj wspólnoty lub osoby…',
  filterLabel: 'Stan',
  filterAll: 'Wszystkie',
  filterErrors: 'Z błędami',
  filterReady: 'Gotowe',
  filterWaiting: 'Niezłożone',
  filterFiled: 'Złożone',
  noMatch: 'Nic nie pasuje do wyszukiwania.',
  loadError: 'Nie udało się wczytać PIT-ów',
  refresh: 'Odśwież',
  // toolbar
  importXml: 'Importuj XML',
  importXmlHint: 'Wczytaj foldery z plikami PIT-11 i PIT-4R z e-Deklaracji (np. z poprzedniego roku)',
  importing: 'Importuję pliki XML…',
  imported: 'Z folderu „{folder}” dodano {n} ({osoby}, {pliki}).',
  importedNothing: 'Z folderu „{folder}” nic nie dodano: {n} już są w tym roku.',
  importedReview: '{n} do przeglądu — oznaczone na liście.',
  importedSkipped: 'Pominięto {n} plików.',
  importError: 'Nie udało się zaimportować XML-i',
  excelTemplate: 'Szablon Excel',
  excelTemplateHint: 'Zapisz arkusz z osobami i zeszłorocznymi kwotami do wypełnienia',
  excelRead: 'Wczytaj Excel',
  excelReadHint: 'Wczytaj wypełniony arkusz z kwotami',
  excelSaved: 'Zapisano szablon: {file}',
  excelTemplateError: 'Nie udało się zapisać szablonu',
  excelReading: 'Wczytuję arkusz…',
  excelRead_ok: 'Z arkusza „{file}” zaktualizowano {n}.',
  excelRead_none: 'Arkusz „{file}” nie zmienił żadnej kwoty.',
  excelRead_skipped: 'Pominięto wierszy: {n}.',
  excelRead_warn: 'Uwagi: {list}',
  excelReadError: 'Nie udało się wczytać arkusza',
  add: 'Dodaj wspólnotę',
  new: 'Nowa wspólnota',
  downloadAll: 'Pobierz wszystko',
  downloadAllHint: 'XML i PDF wszystkich gotowych dokumentów roku {rok}',
  downloadingAll: 'Zapisuję pliki…',
  // empty
  emptyTitle: 'Rok {rok} nie ma jeszcze żadnych PIT-ów',
  emptyCarry: 'Mogę założyć rok {rok} z danych roku {prev}: te same osoby, tytuły i kwoty. To ostatnie znane dane — popraw je ręcznie; rok {prev} zostaje widoczny pod polami jako punkt odniesienia.',
  emptyCarryBtn: 'Przenieś z roku {prev}',
  emptyText: 'Zaimportuj pliki XML z e-Deklaracji albo dodaj wspólnotę ręcznie.',
  seedBtn: 'Zasil z XML i przenieś na {rok}',
  seedTitle: 'Zasil rok {rok} z plików XML',
  seedDesc: 'Wskażesz folder z plikami PIT-11 i PIT-4R z e-Deklaracji. Aplikacja wczyta je jako wskazany rok, a potem przeniesie wszystkie dane (osoby, kwoty, miesiące) na rok {rok}. Kwoty potem poprawiasz ręcznie.',
  seedYear: 'Rok plików XML',
  seedSubmit: 'Wskaż folder i zasil',
  seedDone: 'Wczytano rok {zrok} ({n}) i założono rok {rok}.',
  seedError: 'Nie udało się zasilić roku',
  carried: 'Rok {rok}: założono {n} z danymi z poprzedniego roku — popraw kwoty ręcznie.',
  carryError: 'Nie udało się przenieść roku',
  carryMissing: 'W roku {prev} jest {n}, których nie ma jeszcze w {rok}.',
  carryMissingBtn: 'Dołóż brakujące',
  // rows
  rowAdvances: 'zaliczki',
  rowNip: 'NIP {nip}',
  rowPeople: '{n} osób w PIT-11',
  rowNoPit4r: 'bez PIT-4R',
  rowPit4r: 'PIT-4R {kwota}',
  rowFiled: 'Złożone {when}',
  rowReview: 'do przeglądu',
  rowDocsButton: 'Osoby i PIT-4R ({n})',
  rowExpand: 'Pokaż dokumenty',
  rowCollapse: 'Zwiń dokumenty',
  selectFor: 'Zaznacz do akcji',
  docPit11: 'PIT-11',
  docPit4r: 'PIT-4R',
  docCorrection: 'korekta',
  statusError: 'Braki',
  statusWarn: 'Uwagi',
  statusReady: 'Gotowe',
  filedDone: 'Złożone w MF',
  filedMark: 'Oznacz jako złożone',
  filedUndo: 'Zdejmij',
  filedBy: 'Złożone {when} przez {who}{ref}',
  filedRef: ', nr ref. {ref}',
  selectionBar: 'Zaznaczone dokumenty: {n}',
  batchFiles: 'Pobierz XML i PDF ({n})',
  batchXml: 'Tylko XML',
  batchPdf: 'Tylko PDF',
  batchSign: 'Podpisz ({n})',
  batchFiled: 'Oznacz jako złożone ({n})',
  batchUnfiled: 'Zdejmij „złożone” ({n})',
  // filed modal
  filedTitle: 'Oznacz jako złożone',
  filedSubtitle: 'Dokumentów: {n}',
  filedDesc: 'Zaznaczasz, że te pliki zostały przesłane do e-Deklaracji. Numer referencyjny z bramki zapisze się przy każdym dokumencie (opcjonalnie).',
  filedRefLabel: 'Numer referencyjny',
  filedRefHint: 'Np. z pliku numer-referencyjny-….txt. Jeden numer dla wszystkich zaznaczonych — pusty też jest w porządku.',
  filedSubmit: 'Oznacz',
  filedMarked: 'Oznaczono jako złożone: {n}.',
  filedUnmarked: 'Zdjęto oznaczenie: {n}.',
  filedError: 'Nie udało się zapisać oznaczenia',
  // files / signing
  filesError: 'Nie udało się zapisać plików',
  filesNone: 'Nic nie zapisano: {list}',
  filesDone: 'Zapisano {n} plików w „{folder}”.',
  filesSkipped: 'Pominięto {n}: {list}',
  signTitle: 'Podpisz kwalifikowanym podpisem',
  signSubtitle: 'PIT {rok} · {n}',
  signXmlNote:
    'Podpisany XML (XAdES) to plik, który wczytujesz do e-Deklaracji — „… (podpisany).xml”. PDF jest kopią dla podatnika.',
  signPdfOption: 'Podpisz też PDF (PAdES)',
  signPdfOptionHint: 'Podwaja liczbę podpisów na karcie — zwykle PDF dla podatnika nie wymaga podpisu.',
  signReady: 'Do podpisu: {n}',
  signNothing: 'Żaden z zaznaczonych dokumentów nie jest gotowy — popraw braki i zaznacz ponownie.',
  signSkipped: 'Pominięte z powodu braków ({n}):',
  signMore: 'i jeszcze {n}',
  signSubmit: 'Podpisz {n}',
  signPinHint: 'Jednym PIN-em podpiszesz {n}.',
  // summary
  sumFiles: 'Zapisane pliki',
  sumSigned: 'Podpisane pliki',
  sumFilesSub: 'PIT {rok}',
  sumSignedSub: 'PIT {rok} · {kto}',
  sumSaved: 'Zapisane',
  sumSkipped: 'Pominięte',
  sumUnsigned: 'Niepodpisane',
  sumNothing: 'Nic nie zostało zapisane.',
  sumStopped: 'Przerwano: {reason}',
  sumFolder: 'Folder: {folder}',
  sumOpenFolder: 'Otwórz folder',
  sumSelectRest: 'Zaznacz pozostałe ({n})',
  sumSkippedList: 'Pominięte ({n})',
  sumUnsignedList: 'Niepodpisane ({n})',
  sumSavedList: 'Zapisane ({n})',
  sumFileMissing: 'Tego pliku już nie ma na dysku.',
  // detail
  back: 'Wróć do listy',
  metaYear: 'rok {rok}',
  save: 'Zapisz',
  saved: 'Zapisano.',
  saveError: 'Nie udało się zapisać',
  unsaved: 'Niezapisane zmiany',
  allSaved: 'Wszystko zapisane',
  newNeeds: 'Podaj NIP (10 cyfr) i nazwę wspólnoty.',
  unsavedConfirm: 'Masz niezapisane zmiany. Wyjść bez zapisywania?',
  unsavedDiscard: 'Wyjdź bez zapisu',
  delete: 'Usuń',
  deleteConfirm: 'Usunąć PIT wspólnoty „{name}” za {rok}? Zniknie wraz z osobami i PIT-4R.',
  deleted: 'Usunięto.',
  saveFirst: 'Najpierw zapisz zmiany.',
  platnikTitle: 'Płatnik',
  platnikDesc: 'Wspólnota, która wypłaciła pieniądze: to jej dane trafiają do wszystkich PIT-11 i PIT-4R. NIP-u nie ma na liście Adresów — wpisz go raz, potem pójdzie za wspólnotą z roku na rok.',
  adresyBezPit: 'Wspólnoty z Adresów bez PIT w {rok}: {n}',
  adresyBezPitHint: 'Lista wspólnot to lista z Adresów. Te nie mają jeszcze PIT w tym roku — dodaj te, którym wypłacałeś pieniądze.',
  adresyDodaj: 'Dodaj',
  platnikPick: 'Wybierz wspólnotę z Adresów',
  platnikPickPlaceholder: 'Wybierz wspólnotę…',
  nip: 'NIP płatnika',
  nazwa: 'Nazwa pełna',
  nazwaHint: 'Tak jak w deklaracjach: WSPÓLNOTA MIESZKANIOWA …',
  urzadPlatnika: 'Urząd skarbowy płatnika (PIT-4R)',
  osobyTitle: 'Osoby (PIT-11)',
  osobyDesc: 'Każdy, komu wspólnota wypłaciła pieniądze w roku — jeden PIT-11 na osobę.',
  addPerson: 'Dodaj osobę',
  addPersonFrom: 'Wybierz osobę z innych wspólnot',
  addPersonFromPlaceholder: 'Osoba z innej wspólnoty…',
  noPeople: 'Brak osób — dodaj pierwszą.',
  pickSearch: 'Szukaj…',
  pickEmpty: 'Nic nie znaleziono',
  expandAll: 'Rozwiń wszystkie',
  collapseAll: 'Zwiń wszystkie',
  newPerson: 'Nowa osoba',
  personRemove: 'Usuń osobę',
  personRemoveConfirm: 'Usunąć osobę „{name}” z tej wspólnoty?',
  identitySec: 'Dane podatnika',
  imie: 'Imię',
  nazwisko: 'Nazwisko',
  pesel: 'PESEL',
  peselHint: 'Albo NIP, albo numer zagraniczny poniżej.',
  nipOsoby: 'NIP',
  dataUr: 'Data urodzenia',
  dataFromPesel: 'z PESEL-u',
  urzadOsoby: 'Urząd skarbowy podatnika',
  urzadOsobyHint: 'Wg miejsca zamieszkania podatnika — to inny urząd niż płatnika.',
  urzadPick: 'Wybierz urząd…',
  foreign: 'Numer zagraniczny (cudzoziemiec bez PESEL)',
  nrId: 'Numer',
  rodzajNrId: 'Rodzaj numeru',
  krajWydania: 'Kraj wydania (np. UA)',
  addressSec: 'Adres zamieszkania',
  ulica: 'Ulica',
  nrDomu: 'Nr domu',
  nrLokalu: 'Nr lokalu',
  miejscowosc: 'Miejscowość',
  kod: 'Kod pocztowy',
  wojewodztwo: 'Województwo',
  powiat: 'Powiat',
  titlesSec: 'Za co i ile',
  titlesDesc: 'Wybierz tytuły wypłaty. Zeszłoroczna kwota jest pod polem.',
  tytul_zarzad: 'Zarząd (część F)',
  tytul_zlecenie: 'Umowa zlecenia (wiersz 6)',
  tytul_etat: 'Stosunek pracy (wiersz 1)',
  tytul_art13: 'Art. 13 pkt 2, 4–9 (wiersz 5)',
  zarzadOpis: 'Opis przychodu (poz. 99)',
  zarzadKwota: 'Kwota roczna (poz. 100)',
  przychod: 'Przychód',
  koszty: 'Koszty uzyskania',
  kosztyHint: 'Puste = z reguły: {kwota} (20%, limit {limit} zł).',
  kosztyHintEtat: 'Puste = do limitu {limit} zł.',
  zaliczka: 'Zaliczka pobrana (zł)',
  zaliczkaHintPayroll: 'Z listy płac, w pełnych złotych.',
  zaliczkaHintArt13: 'Puste = 12% dochodu: {kwota} zł.',
  dochodLine: 'Koszty {koszty} · dochód {dochod}',
  skladki: 'Składki ZUS odliczone (poz. 95)',
  zdrowotna: 'Składka zdrowotna (poz. 122)',
  podwyzszone: 'Koszty podwyższone (limit 3 600 zł zamiast 3 000 zł)',
  prevYear: '{rok}: {kwota}',
  prevYearNone: 'brak w {rok}',
  correctionSec: 'Korekta',
  cel: 'Cel złożenia',
  cel1: 'Złożenie',
  cel2: 'Korekta',
  przyczyna: 'Uzasadnienie przyczyn korekty (ORD-ZU)',
  przyczynaHint: 'Trafia do załącznika ORD-ZU; do 1000 znaków.',
  review: 'Do przeglądu po imporcie',
  reviewDesc: 'Import znalazł w plikach coś podejrzanego. Sprawdź i zatwierdź — dopóki tego nie zrobisz, dokument nie wyjdzie.',
  reviewDone: 'Sprawdzone — zdejmij blokadę',
  uwagi: 'Notatka',
  problemsTitle: 'Co jeszcze trzeba poprawić',
  warningsTitle: 'Uwagi (nie blokują)',
  apply: 'Zastosuj dane osoby we wszystkich wspólnotach roku',
  applyHint: 'Imię, nazwisko, PESEL, adres i urząd trafią do tej osoby w {n}.',
  applied: 'Zaktualizowano dane osoby w {n}.',
  applyError: 'Nie udało się zaktualizować pozostałych wspólnot',
  docDownload: 'Pobierz XML i PDF',
  docSign: 'Podpisz',
  pit4rSec: 'PIT-4R — zaliczki miesiąc po miesiącu',
  pit4rDesc: 'Deklaracja roczna płatnika. PIT-11 mają tylko sumy roczne, więc miesięczne kwoty wpisujesz tu.',
  pit4rAdd: 'Dodaj PIT-4R',
  pit4rRemove: 'Usuń PIT-4R',
  pit4rNone: 'Ta wspólnota nie składa PIT-4R w tym roku (nic nie pobrała).',
  pit4rRowEtatLiczba: 'Wiersz 1 — liczba podatników',
  pit4rRowEtatKwota: 'Wiersz 1 — zaliczki (stosunek pracy)',
  pit4rRowArt41: 'Wiersz 3 — zaliczki art. 41 (zlecenia, art. 13)',
  pit4rRowInne: 'Wiersz 4 — inne',
  pit4rRowSuma: 'Wiersz 5 — suma pobranych',
  pit4rRowWplata: 'Do wpłaty do urzędu',
  pit4rTotal: 'Razem',
  pit4rPrev: 'W {rok} razem: {kwota}',
  pit4rCheckEtat: 'Wiersz 1: PIT-4R {pit4r} zł, PIT-11 razem {pit11} zł.',
  pit4rCheckArt41: 'Wiersz 3: PIT-4R {pit4r} zł, PIT-11 razem {pit11} zł.',
  pit4rCheckOk: 'Suma zaliczek PIT-4R zgadza się z PIT-11.',
  pit4rCheckTitle: 'Zgodność z PIT-11',
  pit4rFill: 'Wstaw sumy z PIT-11 do jednego miesiąca',
  pit4rFillMonth: 'Miesiąc…',
  historyTitle: 'Pobrane pliki',
  historyItem: '{when} · {who} · {plik}',
  historyNone: 'Jeszcze nic nie pobrano.',
  problemNip: 'Brak poprawnego NIP-u płatnika (10 cyfr).',
  problemName: 'Brak nazwy płatnika.',
} as const;

type Teksty = { [K in keyof typeof pl]: string };

const en: Teksty = {
  title: 'PIT-11 and PIT-4R',
  heroYear: 'tax year',
  heroEmpty: 'No communities this year',
  heroCount: '{n} communities',
  heroPeople: '{n} PIT-11',
  heroAdvances: 'advances {kwota}',
  heroReview: 'to review: {n}',
  heroFiled: 'filed: {done} of {total}',
  yearNew: '{rok} (new)',
  yearPrev: 'Previous year',
  yearNext: 'Next year',
  year: 'Year',
  formUnconfirmed:
    'The {rok} forms are not confirmed yet: PIT-11 (29) and PIT-4R (13) of the previous year are used. The e-Deklaracje gateway checks the file against its schema — if the Ministry has published a new form, the file is rejected, not wrongly filed.',
  formMissing: 'The app does not know the PIT-11 and PIT-4R forms of {rok} — files cannot be generated.',
  search: 'Search a community or a person…',
  filterLabel: 'State',
  filterAll: 'All',
  filterErrors: 'With errors',
  filterReady: 'Ready',
  filterWaiting: 'Not filed',
  filterFiled: 'Filed',
  noMatch: 'Nothing matches the search.',
  loadError: 'Could not load the PIT data',
  refresh: 'Refresh',
  importXml: 'Import XML',
  importXmlHint: 'Load a folder of PIT-11 and PIT-4R files from e-Deklaracje (e.g. last year\'s)',
  importing: 'Importing XML files…',
  imported: 'From the folder "{folder}" added {n} ({osoby}, {pliki}).',
  importedNothing: 'Nothing added from the folder "{folder}": {n} are already in this year.',
  importedReview: '{n} to review — marked in the list.',
  importedSkipped: '{n} files skipped.',
  importError: 'Could not import the XML files',
  excelTemplate: 'Excel template',
  excelTemplateHint: 'Save a sheet with the people and last year\'s amounts to fill in',
  excelRead: 'Load Excel',
  excelReadHint: 'Load the filled sheet with the amounts',
  excelSaved: 'Template saved: {file}',
  excelTemplateError: 'Could not save the template',
  excelReading: 'Reading the sheet…',
  excelRead_ok: 'From the sheet "{file}" updated {n}.',
  excelRead_none: 'The sheet "{file}" changed no amount.',
  excelRead_skipped: 'Rows skipped: {n}.',
  excelRead_warn: 'Notes: {list}',
  excelReadError: 'Could not read the sheet',
  add: 'Add community',
  new: 'New community',
  downloadAll: 'Download all',
  downloadAllHint: 'XML and PDF of all ready documents of {rok}',
  downloadingAll: 'Writing files…',
  emptyTitle: 'Year {rok} has no PIT data yet',
  emptyCarry: 'I can start {rok} from {prev}: the same people, titles and amounts. These are the last known figures — correct them by hand; {prev} stays visible under the fields as the reference.',
  emptyCarryBtn: 'Carry over from {prev}',
  emptyText: 'Import the XML files from e-Deklaracje or add a community by hand.',
  seedBtn: 'Seed from XML and carry over to {rok}',
  seedTitle: 'Seed {rok} from XML files',
  seedDesc: 'You pick a folder of PIT-11 and PIT-4R files from e-Deklaracje. The app loads them as the year you give, then carries all the data (people, amounts, months) over to {rok}. You correct the amounts by hand afterwards.',
  seedYear: 'Year of the XML files',
  seedSubmit: 'Pick the folder and seed',
  seedDone: 'Loaded {zrok} ({n}) and created {rok}.',
  seedError: 'Could not seed the year',
  carried: 'Year {rok}: {n} created with last year\'s data — correct the amounts by hand.',
  carryError: 'Could not carry the year over',
  carryMissing: '{prev} has {n} that {rok} does not have yet.',
  carryMissingBtn: 'Add the missing ones',
  rowAdvances: 'advances',
  rowNip: 'NIP {nip}',
  rowPeople: '{n} people in PIT-11',
  rowNoPit4r: 'no PIT-4R',
  rowPit4r: 'PIT-4R {kwota}',
  rowFiled: 'Filed {when}',
  rowReview: 'to review',
  rowDocsButton: 'People and PIT-4R ({n})',
  rowExpand: 'Show documents',
  rowCollapse: 'Hide documents',
  selectFor: 'Select for an action',
  docPit11: 'PIT-11',
  docPit4r: 'PIT-4R',
  docCorrection: 'correction',
  statusError: 'Missing',
  statusWarn: 'Notes',
  statusReady: 'Ready',
  filedDone: 'Filed with MF',
  filedMark: 'Mark as filed',
  filedUndo: 'Undo',
  filedBy: 'Filed {when} by {who}{ref}',
  filedRef: ', ref. {ref}',
  selectionBar: 'Documents selected: {n}',
  batchFiles: 'Download XML and PDF ({n})',
  batchXml: 'XML only',
  batchPdf: 'PDF only',
  batchSign: 'Sign ({n})',
  batchFiled: 'Mark as filed ({n})',
  batchUnfiled: 'Undo "filed" ({n})',
  filedTitle: 'Mark as filed',
  filedSubtitle: 'Documents: {n}',
  filedDesc: 'You state that these files were sent to e-Deklaracje. The reference number from the gateway is saved with each document (optional).',
  filedRefLabel: 'Reference number',
  filedRefHint: 'E.g. from numer-referencyjny-….txt. One number for all selected — empty is fine too.',
  filedSubmit: 'Mark',
  filedMarked: 'Marked as filed: {n}.',
  filedUnmarked: 'Mark removed: {n}.',
  filedError: 'Could not save the mark',
  filesError: 'Could not write the files',
  filesNone: 'Nothing written: {list}',
  filesDone: 'Wrote {n} files to "{folder}".',
  filesSkipped: 'Skipped {n}: {list}',
  signTitle: 'Sign with a qualified signature',
  signSubtitle: 'PIT {rok} · {n}',
  signXmlNote:
    'The signed XML (XAdES) is the file you load into e-Deklaracje — "… (podpisany).xml". The PDF is the taxpayer\'s copy.',
  signPdfOption: 'Sign the PDF too (PAdES)',
  signPdfOptionHint: 'Doubles the number of signatures on the card — the taxpayer\'s PDF usually needs none.',
  signReady: 'To sign: {n}',
  signNothing: 'None of the selected documents is ready — fix what is missing and select again.',
  signSkipped: 'Skipped for missing data ({n}):',
  signMore: 'and {n} more',
  signSubmit: 'Sign {n}',
  signPinHint: 'One PIN signs {n}.',
  sumFiles: 'Files written',
  sumSigned: 'Files signed',
  sumFilesSub: 'PIT {rok}',
  sumSignedSub: 'PIT {rok} · {kto}',
  sumSaved: 'Written',
  sumSkipped: 'Skipped',
  sumUnsigned: 'Unsigned',
  sumNothing: 'Nothing was written.',
  sumStopped: 'Stopped: {reason}',
  sumFolder: 'Folder: {folder}',
  sumOpenFolder: 'Open folder',
  sumSelectRest: 'Select the rest ({n})',
  sumSkippedList: 'Skipped ({n})',
  sumUnsignedList: 'Unsigned ({n})',
  sumSavedList: 'Written ({n})',
  sumFileMissing: 'This file is no longer on the disk.',
  back: 'Back to the list',
  metaYear: 'year {rok}',
  save: 'Save',
  saved: 'Saved.',
  saveError: 'Could not save',
  unsaved: 'Unsaved changes',
  allSaved: 'Everything saved',
  newNeeds: 'Enter the NIP (10 digits) and the community\'s name.',
  unsavedConfirm: 'You have unsaved changes. Leave without saving?',
  unsavedDiscard: 'Leave without saving',
  delete: 'Delete',
  deleteConfirm: 'Delete the PIT of "{name}" for {rok}? It goes with its people and the PIT-4R.',
  deleted: 'Deleted.',
  saveFirst: 'Save the changes first.',
  platnikTitle: 'Payer',
  platnikDesc: 'The community that paid the money: its data goes into every PIT-11 and PIT-4R. The Adresy list has no NIP — enter it once, it then follows the community from year to year.',
  adresyBezPit: 'Communities of Adresy with no PIT in {rok}: {n}',
  adresyBezPitHint: 'The list of communities is the Adresy list. These have no PIT this year yet — add the ones you paid money to.',
  adresyDodaj: 'Add',
  platnikPick: 'Pick a community from Adresy',
  platnikPickPlaceholder: 'Pick a community…',
  nip: 'Payer NIP',
  nazwa: 'Full name',
  nazwaHint: 'As in the declarations: WSPÓLNOTA MIESZKANIOWA …',
  urzadPlatnika: 'Payer\'s tax office (PIT-4R)',
  osobyTitle: 'People (PIT-11)',
  osobyDesc: 'Everyone the community paid in the year — one PIT-11 per person.',
  addPerson: 'Add a person',
  addPersonFrom: 'Pick a person from other communities',
  addPersonFromPlaceholder: 'Person from another community…',
  noPeople: 'No people yet — add the first one.',
  pickSearch: 'Search…',
  pickEmpty: 'Nothing found',
  expandAll: 'Expand all',
  collapseAll: 'Collapse all',
  newPerson: 'New person',
  personRemove: 'Remove person',
  personRemoveConfirm: 'Remove "{name}" from this community?',
  identitySec: 'Taxpayer',
  imie: 'First name',
  nazwisko: 'Surname',
  pesel: 'PESEL',
  peselHint: 'Either a NIP or a foreign number below.',
  nipOsoby: 'NIP',
  dataUr: 'Date of birth',
  dataFromPesel: 'from PESEL',
  urzadOsoby: 'Taxpayer\'s tax office',
  urzadOsobyHint: 'By the taxpayer\'s residence — not the payer\'s office.',
  urzadPick: 'Pick an office…',
  foreign: 'Foreign number (foreigner without a PESEL)',
  nrId: 'Number',
  rodzajNrId: 'Kind of number',
  krajWydania: 'Issuing country (e.g. UA)',
  addressSec: 'Home address',
  ulica: 'Street',
  nrDomu: 'House no.',
  nrLokalu: 'Flat no.',
  miejscowosc: 'City',
  kod: 'Postcode',
  wojewodztwo: 'Voivodeship',
  powiat: 'County',
  titlesSec: 'What for and how much',
  titlesDesc: 'Pick the titles of the payment. Last year\'s amount is under the field.',
  tytul_zarzad: 'Board (part F)',
  tytul_zlecenie: 'Mandate contract (row 6)',
  tytul_etat: 'Employment (row 1)',
  tytul_art13: 'Art. 13 pt 2, 4–9 (row 5)',
  zarzadOpis: 'Description of the income (poz. 99)',
  zarzadKwota: 'Yearly amount (poz. 100)',
  przychod: 'Income',
  koszty: 'Deductible costs',
  kosztyHint: 'Empty = by the rule: {kwota} (20%, limit {limit} zł).',
  kosztyHintEtat: 'Empty = up to the {limit} zł limit.',
  zaliczka: 'Advance withheld (zł)',
  zaliczkaHintPayroll: 'From the payroll, in whole złoty.',
  zaliczkaHintArt13: 'Empty = 12% of the income: {kwota} zł.',
  dochodLine: 'Costs {koszty} · income {dochod}',
  skladki: 'ZUS contributions deducted (poz. 95)',
  zdrowotna: 'Health contribution (poz. 122)',
  podwyzszone: 'Increased costs (limit 3 600 zł instead of 3 000 zł)',
  prevYear: '{rok}: {kwota}',
  prevYearNone: 'none in {rok}',
  correctionSec: 'Correction',
  cel: 'Purpose',
  cel1: 'Filing',
  cel2: 'Correction',
  przyczyna: 'Reasons for the correction (ORD-ZU)',
  przyczynaHint: 'Goes into the ORD-ZU attachment; up to 1000 characters.',
  review: 'To review after the import',
  reviewDesc: 'The import found something suspicious in the files. Check it and confirm — until you do, the document is held back.',
  reviewDone: 'Checked — lift the hold',
  uwagi: 'Note',
  problemsTitle: 'What still has to be fixed',
  warningsTitle: 'Notes (do not block)',
  apply: 'Apply this person\'s data to all communities of the year',
  applyHint: 'First name, surname, PESEL, address and office go to this person in {n}.',
  applied: 'Updated the person in {n}.',
  applyError: 'Could not update the other communities',
  docDownload: 'Download XML and PDF',
  docSign: 'Sign',
  pit4rSec: 'PIT-4R — advances month by month',
  pit4rDesc: 'The payer\'s yearly declaration. The PIT-11s hold only yearly sums, so the monthly amounts are entered here.',
  pit4rAdd: 'Add PIT-4R',
  pit4rRemove: 'Remove PIT-4R',
  pit4rNone: 'This community files no PIT-4R this year (it withheld nothing).',
  pit4rRowEtatLiczba: 'Row 1 — number of taxpayers',
  pit4rRowEtatKwota: 'Row 1 — advances (employment)',
  pit4rRowArt41: 'Row 3 — art. 41 advances (mandates, art. 13)',
  pit4rRowInne: 'Row 4 — other',
  pit4rRowSuma: 'Row 5 — total withheld',
  pit4rRowWplata: 'To pay to the tax office',
  pit4rTotal: 'Total',
  pit4rPrev: '{rok} total: {kwota}',
  pit4rCheckEtat: 'Row 1: PIT-4R {pit4r} zł, PIT-11 together {pit11} zł.',
  pit4rCheckArt41: 'Row 3: PIT-4R {pit4r} zł, PIT-11 together {pit11} zł.',
  pit4rCheckOk: 'The PIT-4R advances add up to the PIT-11s.',
  pit4rCheckTitle: 'Agreement with the PIT-11s',
  pit4rFill: 'Put the PIT-11 sums into one month',
  pit4rFillMonth: 'Month…',
  historyTitle: 'Downloaded files',
  historyItem: '{when} · {who} · {plik}',
  historyNone: 'Nothing downloaded yet.',
  problemNip: 'The payer has no valid NIP (10 digits).',
  problemName: 'The payer has no name.',
};

export const PIT_TEXTS: { pl: Teksty; en: Teksty } = { pl, en };
export type PitT = Teksty;
